// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import billing "github.com/paysuper/paysuper-billing-server/pkg/proto/billing"
import mock "github.com/stretchr/testify/mock"

import time "time"

// AccountingServiceInterface is an autogenerated mock type for the AccountingServiceInterface type
type AccountingServiceInterface struct {
	mock.Mock
}

// GetCorrectionsForRoyaltyReport provides a mock function with given fields: merchantId, currency, from, to
func (_m *AccountingServiceInterface) GetCorrectionsForRoyaltyReport(merchantId string, currency string, from time.Time, to time.Time) ([]*billing.AccountingEntry, error) {
	ret := _m.Called(merchantId, currency, from, to)

	var r0 []*billing.AccountingEntry
	if rf, ok := ret.Get(0).(func(string, string, time.Time, time.Time) []*billing.AccountingEntry); ok {
		r0 = rf(merchantId, currency, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*billing.AccountingEntry)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, time.Time, time.Time) error); ok {
		r1 = rf(merchantId, currency, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRollingReservesForRoyaltyReport provides a mock function with given fields: merchantId, currency, from, to
func (_m *AccountingServiceInterface) GetRollingReservesForRoyaltyReport(merchantId string, currency string, from time.Time, to time.Time) ([]*billing.AccountingEntry, error) {
	ret := _m.Called(merchantId, currency, from, to)

	var r0 []*billing.AccountingEntry
	if rf, ok := ret.Get(0).(func(string, string, time.Time, time.Time) []*billing.AccountingEntry); ok {
		r0 = rf(merchantId, currency, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*billing.AccountingEntry)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, time.Time, time.Time) error); ok {
		r1 = rf(merchantId, currency, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
