// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import billingpb "github.com/paysuper/paysuper-proto/go/billingpb"
import context "context"
import mock "github.com/stretchr/testify/mock"

// KeyProductRepositoryInterface is an autogenerated mock type for the KeyProductRepositoryInterface type
type KeyProductRepositoryInterface struct {
	mock.Mock
}

// GetById provides a mock function with given fields: _a0, _a1
func (_m *KeyProductRepositoryInterface) GetById(_a0 context.Context, _a1 string) (*billingpb.KeyProduct, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *billingpb.KeyProduct
	if rf, ok := ret.Get(0).(func(context.Context, string) *billingpb.KeyProduct); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billingpb.KeyProduct)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: _a0, _a1
func (_m *KeyProductRepositoryInterface) Update(_a0 context.Context, _a1 *billingpb.KeyProduct) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *billingpb.KeyProduct) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
