// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import billingpb "github.com/paysuper/paysuper-proto/go/billingpb"
import context "context"
import mock "github.com/stretchr/testify/mock"
import pkg "github.com/paysuper/paysuper-billing-server/internal/pkg"

// MoneyBackCostSystemRepositoryInterface is an autogenerated mock type for the MoneyBackCostSystemRepositoryInterface type
type MoneyBackCostSystemRepositoryInterface struct {
	mock.Mock
}

// Delete provides a mock function with given fields: _a0, _a1
func (_m *MoneyBackCostSystemRepositoryInterface) Delete(_a0 context.Context, _a1 *billingpb.MoneyBackCostSystem) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *billingpb.MoneyBackCostSystem) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4, _a5, _a6, _a7, _a8
func (_m *MoneyBackCostSystemRepositoryInterface) Find(_a0 context.Context, _a1 string, _a2 string, _a3 string, _a4 string, _a5 string, _a6 string, _a7 string, _a8 int32) ([]*pkg.MoneyBackCostSystemSet, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4, _a5, _a6, _a7, _a8)

	var r0 []*pkg.MoneyBackCostSystemSet
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string, string, int32) []*pkg.MoneyBackCostSystemSet); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4, _a5, _a6, _a7, _a8)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*pkg.MoneyBackCostSystemSet)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string, string, string, int32) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3, _a4, _a5, _a6, _a7, _a8)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: _a0
func (_m *MoneyBackCostSystemRepositoryInterface) GetAll(_a0 context.Context) (*billingpb.MoneyBackCostSystemList, error) {
	ret := _m.Called(_a0)

	var r0 *billingpb.MoneyBackCostSystemList
	if rf, ok := ret.Get(0).(func(context.Context) *billingpb.MoneyBackCostSystemList); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billingpb.MoneyBackCostSystemList)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: _a0, _a1
func (_m *MoneyBackCostSystemRepositoryInterface) GetById(_a0 context.Context, _a1 string) (*billingpb.MoneyBackCostSystem, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *billingpb.MoneyBackCostSystem
	if rf, ok := ret.Get(0).(func(context.Context, string) *billingpb.MoneyBackCostSystem); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billingpb.MoneyBackCostSystem)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: _a0, _a1
func (_m *MoneyBackCostSystemRepositoryInterface) Insert(_a0 context.Context, _a1 *billingpb.MoneyBackCostSystem) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *billingpb.MoneyBackCostSystem) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MultipleInsert provides a mock function with given fields: _a0, _a1
func (_m *MoneyBackCostSystemRepositoryInterface) MultipleInsert(_a0 context.Context, _a1 []*billingpb.MoneyBackCostSystem) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*billingpb.MoneyBackCostSystem) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: _a0, _a1
func (_m *MoneyBackCostSystemRepositoryInterface) Update(_a0 context.Context, _a1 *billingpb.MoneyBackCostSystem) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *billingpb.MoneyBackCostSystem) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
