// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import billing "github.com/paysuper/paysuper-billing-server/pkg/proto/billing"
import bson "github.com/globalsign/mgo/bson"
import mock "github.com/stretchr/testify/mock"
import paylink "github.com/paysuper/paysuper-billing-server/pkg/proto/paylink"

import time "time"

// OrderViewServiceInterface is an autogenerated mock type for the OrderViewServiceInterface type
type OrderViewServiceInterface struct {
	mock.Mock
}

// CountTransactions provides a mock function with given fields: match
func (_m *OrderViewServiceInterface) CountTransactions(match bson.M) (int, error) {
	ret := _m.Called(match)

	var r0 int
	if rf, ok := ret.Get(0).(func(bson.M) int); ok {
		r0 = rf(match)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(bson.M) error); ok {
		r1 = rf(match)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrderBy provides a mock function with given fields: id, uuid, merchantId, receiver
func (_m *OrderViewServiceInterface) GetOrderBy(id string, uuid string, merchantId string, receiver interface{}) (interface{}, error) {
	ret := _m.Called(id, uuid, merchantId, receiver)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(string, string, string, interface{}) interface{}); ok {
		r0 = rf(id, uuid, merchantId, receiver)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string, interface{}) error); ok {
		r1 = rf(id, uuid, merchantId, receiver)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaylinkStat provides a mock function with given fields: paylinkId, merchantId, from, to
func (_m *OrderViewServiceInterface) GetPaylinkStat(paylinkId string, merchantId string, from int64, to int64) (*paylink.StatCommon, error) {
	ret := _m.Called(paylinkId, merchantId, from, to)

	var r0 *paylink.StatCommon
	if rf, ok := ret.Get(0).(func(string, string, int64, int64) *paylink.StatCommon); ok {
		r0 = rf(paylinkId, merchantId, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paylink.StatCommon)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, int64, int64) error); ok {
		r1 = rf(paylinkId, merchantId, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaylinkStatByCountry provides a mock function with given fields: paylinkId, merchantId, from, to
func (_m *OrderViewServiceInterface) GetPaylinkStatByCountry(paylinkId string, merchantId string, from int64, to int64) (*paylink.GroupStatCommon, error) {
	ret := _m.Called(paylinkId, merchantId, from, to)

	var r0 *paylink.GroupStatCommon
	if rf, ok := ret.Get(0).(func(string, string, int64, int64) *paylink.GroupStatCommon); ok {
		r0 = rf(paylinkId, merchantId, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paylink.GroupStatCommon)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, int64, int64) error); ok {
		r1 = rf(paylinkId, merchantId, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaylinkStatByDate provides a mock function with given fields: paylinkId, merchantId, from, to
func (_m *OrderViewServiceInterface) GetPaylinkStatByDate(paylinkId string, merchantId string, from int64, to int64) (*paylink.GroupStatCommon, error) {
	ret := _m.Called(paylinkId, merchantId, from, to)

	var r0 *paylink.GroupStatCommon
	if rf, ok := ret.Get(0).(func(string, string, int64, int64) *paylink.GroupStatCommon); ok {
		r0 = rf(paylinkId, merchantId, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paylink.GroupStatCommon)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, int64, int64) error); ok {
		r1 = rf(paylinkId, merchantId, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaylinkStatByReferrer provides a mock function with given fields: paylinkId, merchantId, from, to
func (_m *OrderViewServiceInterface) GetPaylinkStatByReferrer(paylinkId string, merchantId string, from int64, to int64) (*paylink.GroupStatCommon, error) {
	ret := _m.Called(paylinkId, merchantId, from, to)

	var r0 *paylink.GroupStatCommon
	if rf, ok := ret.Get(0).(func(string, string, int64, int64) *paylink.GroupStatCommon); ok {
		r0 = rf(paylinkId, merchantId, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paylink.GroupStatCommon)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, int64, int64) error); ok {
		r1 = rf(paylinkId, merchantId, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaylinkStatByUtm provides a mock function with given fields: paylinkId, merchantId, from, to
func (_m *OrderViewServiceInterface) GetPaylinkStatByUtm(paylinkId string, merchantId string, from int64, to int64) (*paylink.GroupStatCommon, error) {
	ret := _m.Called(paylinkId, merchantId, from, to)

	var r0 *paylink.GroupStatCommon
	if rf, ok := ret.Get(0).(func(string, string, int64, int64) *paylink.GroupStatCommon); ok {
		r0 = rf(paylinkId, merchantId, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*paylink.GroupStatCommon)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, int64, int64) error); ok {
		r1 = rf(paylinkId, merchantId, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoyaltySummary provides a mock function with given fields: merchantId, currency, from, to
func (_m *OrderViewServiceInterface) GetRoyaltySummary(merchantId string, currency string, from time.Time, to time.Time) ([]*billing.RoyaltyReportProductSummaryItem, *billing.RoyaltyReportProductSummaryItem, error) {
	ret := _m.Called(merchantId, currency, from, to)

	var r0 []*billing.RoyaltyReportProductSummaryItem
	if rf, ok := ret.Get(0).(func(string, string, time.Time, time.Time) []*billing.RoyaltyReportProductSummaryItem); ok {
		r0 = rf(merchantId, currency, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*billing.RoyaltyReportProductSummaryItem)
		}
	}

	var r1 *billing.RoyaltyReportProductSummaryItem
	if rf, ok := ret.Get(1).(func(string, string, time.Time, time.Time) *billing.RoyaltyReportProductSummaryItem); ok {
		r1 = rf(merchantId, currency, from, to)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*billing.RoyaltyReportProductSummaryItem)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string, string, time.Time, time.Time) error); ok {
		r2 = rf(merchantId, currency, from, to)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetTransactionsPrivate provides a mock function with given fields: match, limit, offset
func (_m *OrderViewServiceInterface) GetTransactionsPrivate(match bson.M, limit int, offset int) ([]*billing.OrderViewPrivate, error) {
	ret := _m.Called(match, limit, offset)

	var r0 []*billing.OrderViewPrivate
	if rf, ok := ret.Get(0).(func(bson.M, int, int) []*billing.OrderViewPrivate); ok {
		r0 = rf(match, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*billing.OrderViewPrivate)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(bson.M, int, int) error); ok {
		r1 = rf(match, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTransactionsPublic provides a mock function with given fields: match, limit, offset
func (_m *OrderViewServiceInterface) GetTransactionsPublic(match bson.M, limit int, offset int) ([]*billing.OrderViewPublic, error) {
	ret := _m.Called(match, limit, offset)

	var r0 []*billing.OrderViewPublic
	if rf, ok := ret.Get(0).(func(bson.M, int, int) []*billing.OrderViewPublic); ok {
		r0 = rf(match, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*billing.OrderViewPublic)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(bson.M, int, int) error); ok {
		r1 = rf(match, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
