// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	billing "github.com/paysuper/paysuper-billing-server/pkg/proto/billing"

	mock "github.com/stretchr/testify/mock"
)

// PaymentMinLimitSystemInterface is an autogenerated mock type for the PaymentMinLimitSystemInterface type
type PaymentMinLimitSystemInterface struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: ctx
func (_m *PaymentMinLimitSystemInterface) GetAll(ctx context.Context) ([]*billing.PaymentMinLimitSystem, error) {
	ret := _m.Called(ctx)

	var r0 []*billing.PaymentMinLimitSystem
	if rf, ok := ret.Get(0).(func(context.Context) []*billing.PaymentMinLimitSystem); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*billing.PaymentMinLimitSystem)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByCurrency provides a mock function with given fields: ctx, currency
func (_m *PaymentMinLimitSystemInterface) GetByCurrency(ctx context.Context, currency string) (*billing.PaymentMinLimitSystem, error) {
	ret := _m.Called(ctx, currency)

	var r0 *billing.PaymentMinLimitSystem
	if rf, ok := ret.Get(0).(func(context.Context, string) *billing.PaymentMinLimitSystem); ok {
		r0 = rf(ctx, currency)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.PaymentMinLimitSystem)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, currency)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MultipleInsert provides a mock function with given fields: ctx, pmlsArray
func (_m *PaymentMinLimitSystemInterface) MultipleInsert(ctx context.Context, pmlsArray []*billing.PaymentMinLimitSystem) error {
	ret := _m.Called(ctx, pmlsArray)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*billing.PaymentMinLimitSystem) error); ok {
		r0 = rf(ctx, pmlsArray)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Upsert provides a mock function with given fields: ctx, pmls
func (_m *PaymentMinLimitSystemInterface) Upsert(ctx context.Context, pmls *billing.PaymentMinLimitSystem) error {
	ret := _m.Called(ctx, pmls)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *billing.PaymentMinLimitSystem) error); ok {
		r0 = rf(ctx, pmls)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
