// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import billing "github.com/paysuper/paysuper-billing-server/pkg/proto/billing"
import context "context"
import mock "github.com/stretchr/testify/mock"

// RefundRepositoryInterface is an autogenerated mock type for the RefundRepositoryInterface type
type RefundRepositoryInterface struct {
	mock.Mock
}

// CountByOrderUuid provides a mock function with given fields: _a0, _a1
func (_m *RefundRepositoryInterface) CountByOrderUuid(_a0 context.Context, _a1 string) (int64, error) {
	ret := _m.Called(_a0, _a1)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByOrderUuid provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *RefundRepositoryInterface) FindByOrderUuid(_a0 context.Context, _a1 string, _a2 int64, _a3 int64) ([]*billing.Refund, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	var r0 []*billing.Refund
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) []*billing.Refund); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*billing.Refund)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int64) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAmountByOrderId provides a mock function with given fields: _a0, _a1
func (_m *RefundRepositoryInterface) GetAmountByOrderId(_a0 context.Context, _a1 string) (float64, error) {
	ret := _m.Called(_a0, _a1)

	var r0 float64
	if rf, ok := ret.Get(0).(func(context.Context, string) float64); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(float64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: _a0, _a1
func (_m *RefundRepositoryInterface) GetById(_a0 context.Context, _a1 string) (*billing.Refund, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *billing.Refund
	if rf, ok := ret.Get(0).(func(context.Context, string) *billing.Refund); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.Refund)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: _a0, _a1
func (_m *RefundRepositoryInterface) Insert(_a0 context.Context, _a1 *billing.Refund) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *billing.Refund) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: _a0, _a1
func (_m *RefundRepositoryInterface) Update(_a0 context.Context, _a1 *billing.Refund) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *billing.Refund) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
