{{- $deployment := .Values.backend -}}
{{- $deploymentName := printf "%s-%s" .Release.Name $deployment.name }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ .Chart.Name }}-vat"
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: {{ $deployment.role }}
  annotations: 
    released: {{ .Release.Time }} 
spec:
  schedule: 59 23 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: "{{ .Chart.Name }}-vat-reports"
            image: {{ $deployment.image }}:{{ $deployment.imageTag }}
            command: ["/application/bin/paysuper_billing_service"]
            args: ["-task=vat_reports"]
            env:
            - name: MICRO_SERVER_ADDRESS
              value: "0.0.0.0:{{ $deployment.port }}"
            - name: MICRO_REGISTRY
              value: "mdns"
            - name: MICRO_SELECTOR
              value: "static"
            - name: METRICS_PORT
              value: "{{ $deployment.healthPort }}"   
            {{- range .Values.backend.env }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: {{ $deploymentName }}-env
                  key: {{ . }}
            {{- end }}
          restartPolicy: OnFailure 
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ .Chart.Name }}-rlty"
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: {{ $deployment.role }}
  annotations: 
    released: {{ .Release.Time }} 
spec:
  schedule: 0 8 * * 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: "{{ .Chart.Name }}-royalty-reports"
            image: {{ $deployment.image }}:{{ $deployment.imageTag }}
            command: ["/application/bin/paysuper_billing_service"]
            args: ["-task=royalty_reports"]
            env:
            - name: MICRO_SERVER_ADDRESS
              value: "0.0.0.0:{{ $deployment.port }}"
            - name: MICRO_REGISTRY
              value: "mdns"
            - name: MICRO_SELECTOR
              value: "static"
            - name: METRICS_PORT
              value: "{{ $deployment.healthPort }}"   
            {{- range .Values.backend.env }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: {{ $deploymentName }}-env
                  key: {{ . }}
            {{- end }}
          restartPolicy: OnFailure 
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ .Chart.Name }}-rlty-acpt"
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: {{ $deployment.role }}
  annotations: 
    released: {{ .Release.Time }} 
spec:
  schedule: 59 23 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: "{{ .Chart.Name }}-royalty-reports-accept"
            image: {{ $deployment.image }}:{{ $deployment.imageTag }}
            command: ["/bin/sh","-c"]
            args: ["/application/bin/paysuper_billing_service -task=royalty_reports_accept && /application/bin/paysuper_billing_service -task=create_payouts"]
            env:
            - name: MICRO_SERVER_ADDRESS
              value: "0.0.0.0:{{ $deployment.port }}"
            - name: MICRO_REGISTRY
              value: "mdns"
            - name: MICRO_SELECTOR
              value: "static"
            - name: METRICS_PORT
              value: "{{ $deployment.healthPort }}"            
            {{- range .Values.backend.env }}
            - name: {{ . }}
              valueFrom:
                secretKeyRef:
                  name: {{ $deploymentName }}-env
                  key: {{ . }}
            {{- end }}
          restartPolicy: OnFailure
