// Code generated by mockery v1.0.0. DO NOT EDIT.

package mock

import billing "github.com/paysuper/paysuper-billing-server/pkg/proto/billing"
import mock "github.com/stretchr/testify/mock"

// KeyRepositoryInterface is an autogenerated mock type for the KeyRepositoryInterface type
type KeyRepositoryInterface struct {
	mock.Mock
}

// CancelById provides a mock function with given fields: _a0
func (_m *KeyRepositoryInterface) CancelById(_a0 string) (*billing.Key, error) {
	ret := _m.Called(_a0)

	var r0 *billing.Key
	if rf, ok := ret.Get(0).(func(string) *billing.Key); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.Key)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountKeysByProductPlatform provides a mock function with given fields: _a0, _a1
func (_m *KeyRepositoryInterface) CountKeysByProductPlatform(_a0 string, _a1 string) (int, error) {
	ret := _m.Called(_a0, _a1)

	var r0 int
	if rf, ok := ret.Get(0).(func(string, string) int); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FinishRedeemById provides a mock function with given fields: _a0
func (_m *KeyRepositoryInterface) FinishRedeemById(_a0 string) (*billing.Key, error) {
	ret := _m.Called(_a0)

	var r0 *billing.Key
	if rf, ok := ret.Get(0).(func(string) *billing.Key); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.Key)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: _a0
func (_m *KeyRepositoryInterface) GetById(_a0 string) (*billing.Key, error) {
	ret := _m.Called(_a0)

	var r0 *billing.Key
	if rf, ok := ret.Get(0).(func(string) *billing.Key); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.Key)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: _a0
func (_m *KeyRepositoryInterface) Insert(_a0 *billing.Key) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*billing.Key) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReserveKey provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *KeyRepositoryInterface) ReserveKey(_a0 string, _a1 string, _a2 string, _a3 int32) (*billing.Key, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	var r0 *billing.Key
	if rf, ok := ret.Get(0).(func(string, string, string, int32) *billing.Key); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.Key)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string, int32) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
