// Code generated by mockery v1.0.0. DO NOT EDIT.

package mock

import billing "github.com/paysuper/paysuper-billing-server/pkg/proto/billing"
import mock "github.com/stretchr/testify/mock"

// PaymentSystemServiceInterface is an autogenerated mock type for the PaymentSystemServiceInterface type
type PaymentSystemServiceInterface struct {
	mock.Mock
}

// GetById provides a mock function with given fields: _a0
func (_m *PaymentSystemServiceInterface) GetById(_a0 string) (*billing.PaymentSystem, error) {
	ret := _m.Called(_a0)

	var r0 *billing.PaymentSystem
	if rf, ok := ret.Get(0).(func(string) *billing.PaymentSystem); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*billing.PaymentSystem)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: _a0
func (_m *PaymentSystemServiceInterface) Insert(_a0 *billing.PaymentSystem) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*billing.PaymentSystem) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MultipleInsert provides a mock function with given fields: _a0
func (_m *PaymentSystemServiceInterface) MultipleInsert(_a0 []*billing.PaymentSystem) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func([]*billing.PaymentSystem) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: _a0
func (_m *PaymentSystemServiceInterface) Update(_a0 *billing.PaymentSystem) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*billing.PaymentSystem) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
