// Code generated by mockery v1.0.0. DO NOT EDIT.

package mock

import billing "github.com/paysuper/paysuper-billing-server/pkg/proto/billing"
import mock "github.com/stretchr/testify/mock"

// PayoutDocumentServiceInterface is an autogenerated mock type for the PayoutDocumentServiceInterface type
type PayoutDocumentServiceInterface struct {
	mock.Mock
}

// Insert provides a mock function with given fields: document, ip, source
func (_m *PayoutDocumentServiceInterface) Insert(document *billing.PayoutDocument, ip string, source string) error {
	ret := _m.Called(document, ip, source)

	var r0 error
	if rf, ok := ret.Get(0).(func(*billing.PayoutDocument, string, string) error); ok {
		r0 = rf(document, ip, source)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: document, ip, source
func (_m *PayoutDocumentServiceInterface) Update(document *billing.PayoutDocument, ip string, source string) error {
	ret := _m.Called(document, ip, source)

	var r0 error
	if rf, ok := ret.Get(0).(func(*billing.PayoutDocument, string, string) error); ok {
		r0 = rf(document, ip, source)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
